### ISSUE TITLE
Bug/Crash ticking entity 1.21.0

### ISSUE THREAD

**Issue by Lucifer0894** [st0x0ef/stellaris#12]
upon placing a rocket station, it breaks the chunk and surrounding chunks

Error log - https://mclo.gs/z3AQWH7

**Comment by st0x0ef** [comment]
Fixed in 1.0.3

**Comment by Lucifer0894** [comment]
did some testing around with a single player and found almost every block (fuel refinery, generators and vacuumator) does the same thing rocket station did, is that fixed in 1.0.3 aswell?

**Comment by st0x0ef** [comment]
should be

**Comment by st0x0ef** [comment]
Weird, I've added the missing method... Is it still the same crash log?

**Comment by Lucifer0894** [comment]
https://mclo.gs/dGGMeUz

**Comment by Lucifer0894** [comment]
the game also seems to crash upon clicking planets in the planet selection menu. client sided though, only minecraft not the server(no crash log)

**Comment by makumaku1974** [comment]
since i reported this at first. I have a minor bug to show you. 

I would be using Astrocraft for Stars Cosmetic of the sky. The stars with Stellaris turns them into static asteroids.
![image](https://github.com/user-attachments/assets/7de04d16-86f9-4c47-8c8f-5722e872a5c2)

**Comment by makumaku1974** [comment]
Also, somehow I cant mine with all pickaxes.

**Comment by Lucifer0894** [comment]
yeah. i just booted up my most current 1.0.3(curseforge version), and all pickaxe were broken and couldn't mine any block with any pickaxe, even modded ones

**Comment by eirmax** [comment]
in the next update we are going to change the rendering of the sky in the game

**Comment by st0x0ef** [comment]
> since i reported this at first. I have a minor bug to show you.
> 
> I would be using Astrocraft for Stars Cosmetic of the sky. The stars with Stellaris turns them into static asteroids. ![image](https://private-user-images.githubusercontent.com/129804277/357246437-7de04d16-86f9-4c47-8c8f-5722e872a5c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTQ4MzAsIm5iZiI6MTcyMzU1NDUzMCwicGF0aCI6Ii8xMjk4MDQyNzcvMzU3MjQ2NDM3LTdkZTA0ZDE2LTg2ZjktNGM0Ny04YzhmLTU3MjJlODcyYTVjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMzA4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTdlY2ExZjFiMTkzNWIyNDU3YmM2ZWE5ODNkY2I3ZGNlNTM5NjhkOTIxYTdjNzlhM2RhYTNmMTU4MGU1YzQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7VK8s1QrryG9Sn9vRntjNd_wfSb62DnOksWGcWFzIxo)

you can turn off custom sky rendering in the config

**Comment by Lucifer0894** [comment]
seems to still crash when placing rocket station even in 1.0.4

**Comment by st0x0ef** [comment]
Can I know what other mod you're using, because I'm unable to reproduce your issue, the rocket station work fine for me (maybe you can try without any other mod). I've tried to add the missing method but that cause a conflict when building.

**Comment by NovaAndrom3da** [comment]
I've also got the same issues with 1.0.4 with the fuel refinery.

```
[19:08:29] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1025) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:299) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.AbstractMethodError: Receiver class com.st0x0ef.stellaris.common.blocks.entities.machines.FuelRefineryBlockEntity does not define or inherit an implementation of the resolved method 'abstract net.minecraft.class_1799 method_59984(int)' of interface net.minecraft.class_9695.
	at net.minecraft.class_9695.method_59987(class_9695.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_59993(class_1863.java:90) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_42299(class_1863.java:86) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863$1.method_42303(class_1863.java:189) ~[server-intermediary.jar:?]
	at com.st0x0ef.stellaris.common.blocks.entities.machines.FuelRefineryBlockEntity.tick(FuelRefineryBlockEntity.java:40) ~[stellaris-1.21-fabric-1.0.4.jar:?]
	at com.st0x0ef.stellaris.common.blocks.machines.BaseTickingEntityBlock.lambda$getTicker$0(BaseTickingEntityBlock.java:24) ~[stellaris-1.21-fabric-1.0.4.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:683) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:737) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:488) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:413) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) ~[server-intermediary.jar:?]
	... 5 more
```

I'll test in a moment without any other mods to see if anything changes.

**Comment by NovaAndrom3da** [comment]
Yup, still crashes for me on fabric 0.16.0 MC 1.21 with just architectury, fabric api, stellaris, and JEI. I'll take a look at the codebase to see if theres anything I can do to fix this issue

**Comment by Lucifer0894** [comment]
its hard to list them with text so
![image_2024-08-14_170548620](https://github.com/user-attachments/assets/fa795df9-0d1f-4f22-9a27-7c46f3869a12)
![image_2024-08-14_170600439](https://github.com/user-attachments/assets/be27df51-efd8-4667-bac4-0e4fdad94beb)
![image_2024-08-14_170615782](https://github.com/user-attachments/assets/fea9c42d-f602-426e-aec5-33da4ae7061f)
![image_2024-08-14_170625040](https://github.com/user-attachments/assets/94d6aad8-f31e-4741-a985-f856b6641428)
![image_2024-08-14_170637519](https://github.com/user-attachments/assets/c9902f0e-104c-46a5-8af7-250128a512ac)

**Comment by Lucifer0894** [comment]
the stellaris is currently updated to 1.0.2 because anything past that seems to break my server, but at any notice i do update the mod to most concurrent version and test

**Comment by Lucifer0894** [comment]
balm and snow under trees are 1 version beneath concurrent because of issues with them being most current update

**Comment by NovaAndrom3da** [comment]
I was also having this issue on 1.0.2, for the record

**Comment by Lucifer0894** [comment]
yes but in 1.0.3 i was unable to mine anything so i resorted back to 1.0.2 for functionality

**Comment by st0x0ef** [comment]
> yes but in 1.0.3 i was unable to mine anything so i resorted back to 1.0.2 for functionality

That was fixed in 1.0.4. I'm still unable to reproduce your bug, can you come on the discord server so I'll be able to help you better?

**Comment by st0x0ef** [comment]
> I've also got the same issues with 1.0.4 with the fuel refinery.
> 
> ```
> [19:08:29] [Server thread/ERROR]: Encountered an unexpected exception
> net.minecraft.class_148: Ticking block entity
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1025) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_3176.method_3813(class_3176.java:299) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
> 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
> Caused by: java.lang.AbstractMethodError: Receiver class com.st0x0ef.stellaris.common.blocks.entities.machines.FuelRefineryBlockEntity does not define or inherit an implementation of the resolved method 'abstract net.minecraft.class_1799 method_59984(int)' of interface net.minecraft.class_9695.
> 	at net.minecraft.class_9695.method_59987(class_9695.java:12) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1863.method_59993(class_1863.java:90) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1863.method_42299(class_1863.java:86) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1863$1.method_42303(class_1863.java:189) ~[server-intermediary.jar:?]
> 	at com.st0x0ef.stellaris.common.blocks.entities.machines.FuelRefineryBlockEntity.tick(FuelRefineryBlockEntity.java:40) ~[stellaris-1.21-fabric-1.0.4.jar:?]
> 	at com.st0x0ef.stellaris.common.blocks.machines.BaseTickingEntityBlock.lambda$getTicker$0(BaseTickingEntityBlock.java:24) ~[stellaris-1.21-fabric-1.0.4.jar:?]
> 	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:683) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:737) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_1937.method_18471(class_1937.java:488) ~[server-intermediary.jar:?]
> 	at net.minecraft.class_3218.method_18765(class_3218.java:413) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) ~[server-intermediary.jar:?]
> 	... 5 more
> ```
> 
> I'll test in a moment without any other mods to see if anything changes.

![2024-08-16_08 45 12](https://github.com/user-attachments/assets/8e97e6b4-3506-42f1-a1b5-554c569f8c5f)

**Comment by st0x0ef** [comment]
> Yup, still crashes for me on fabric 0.16.0 MC 1.21 with just architectury, fabric api, stellaris, and JEI. I'll take a look at the codebase to see if theres anything I can do to fix this issue. Downgrading to fabric 0.15.11 makes no difference.

Try replacing jei with rei

**Comment by makumaku1974** [comment]
> > Yup, still crashes for me on fabric 0.16.0 MC 1.21 with just architectury, fabric api, stellaris, and JEI. I'll take a look at the codebase to see if theres anything I can do to fix this issue. Downgrading to fabric 0.15.11 makes no difference.
> 
> Try replacing jei with rei

why not emi?

**Comment by NovaAndrom3da** [comment]
> > Yup, still crashes for me on fabric 0.16.0 MC 1.21 with just architectury, fabric api, stellaris, and JEI. I'll take a look at the codebase to see if theres anything I can do to fix this issue. Downgrading to fabric 0.15.11 makes no difference.
> 
> Try replacing jei with rei

I dont see how that would make much difference since it crashes immediately upon being loaded into a chunk/placed but I guess I could try it.

**Comment by st0x0ef** [comment]
fixed in 1.0.5
