### ISSUE TITLE
[Bug] Crash when teleporting between dimensions (planets)

### ISSUE THREAD

**Issue by alexmozaidze** [st0x0ef/stellaris#50]
The game crashes when switching dimensions, which is most likely caused by an unfortunate mixin somewhere in another mod, though, I am not sure which one.

<details><summary>Server mods</summary>

- ACE_mc1.20.6-3.1.1.jar
- Amplified_Nether_1.21.x_v1.2.6.jar
- antixray-fabric-1.4.6+1.21.1.jar
- architectury-13.0.8-fabric.jar
- balanced-ice-boats-1.0.0.jar
- better_climbing-fabric-3.jar
- BOMD-1.10.2-1.21.1.jar
- c2me-fabric-mc1.21.1-0.3.0+alpha.0.295.jar
- cardinal-components-api-6.1.1.jar
- carpet-extra-1.21-1.4.148.jar
- carryon-fabric-1.21.1-2.2.2.11.jar
- cc-tweaked-1.21.1-fabric-1.114.0.jar
- Chunky-1.4.16.jar
- cloth-config-15.0.140-fabric.jar
- combat_roll-fabric-2.0.1+1.21.1.jar
- CombatNouveau-v21.1.1-1.21.1-Fabric.jar
- common-networking-fabric-1.0.16-1.21.1.jar
- Debugify-1.21.1+1.0.jar
- deeperdarker-fabric-1.21-1.3.2.1.jar
- desert-scourge-1.2.jar
- dungeons-and-taverns-v4.4.4.jar
- easyauth-mc1.21-3.0.25.jar
- edf-remastered-5.0-beta4.jar
- fabric-api-0.107.0+1.21.1.jar
- fabric-carpet-1.21-1.4.147+v240613.jar
- fabric-language-kotlin-1.12.3+kotlin.2.0.21.jar
- ferritecore-7.0.2-hotfix-fabric.jar
- ForgeConfigAPIPort-v21.1.2-1.21.1-Fabric.jar
- formidulus-0.1.0-beta.jar
- geckolib-fabric-1.21.1-4.7.jar
- glow_ink_plus-fabric-1.21-1.2.jar
- herdspanic-1.1.1.jar
- Icarus-Fabric-4.2.0.jar
- Improved_Anvils-1.1.1-1.21.jar
- Incendium_1.21_UNSUPPORTED_PORT_v5.4.3.jar
- item-components-1.1+1.21.jar
- ledger-1.3.4.jar
- lithium-fabric-mc1.21.1-0.13.1.jar
- modernfix-fabric-5.19.5+mc1.21.1.jar
- monsters-in-the-closet-1.0.3+1.21.jar
- netheriteextras-0.4.0+mc1.21.jar
- noisium-fabric-2.3.0+mc1.21-1.21.1.jar
- Nullscape_1.21.x_v1.2.9.jar
- owo-lib-0.12.15+1.21.jar
- pathspeed-1.21_1.0.0.jar
- player-animation-lib-fabric-2.0.0-alpha1+1.21.jar
- PuzzlesLib-v21.1.22-1.21.1-Fabric.jar
- RecipeCooldown-1.0.0.jar
- resourcefulconfig-fabric-1.21-3.0.7.jar
- ScalableLux-0.1.0+fabric.26c6e72-all.jar
- servux-fabric-1.21.0-0.3.7.jar
- skinrestorer-2.1.0+1.21-fabric.jar
- skippy-pearls-1.21.jar
- spark-1.10.109-fabric.jar
- stellaris-1.21-fabric-1.1.7.jar
- styled-chat-2.6.0+1.21.jar
- surveyor-0.6.25+1.21.jar
- SwordBlockingMechanics-v21.1.0-1.21.1-Fabric.jar
- 'TAB v5.0.1.jar'
- Terralith_1.21.x_v2.5.6.jar
- toms_storage_fabric-1.21-2.0.11.jar
- tool-trims-mod-v2-2-1a.jar
- travelersbackpack-fabric-1.21.1-10.1.3.jar
- trinkets-3.10.0.jar
- tt20-0.7.0+mc1.21.jar
- voicechat-fabric-1.21.1-2.5.25.jar
- wandering-illusioner-atlasplays-1.1.0.jar
- withering-heights-v1.0.jar
- worldedit-mod-7.3.8.jar
- Xaeros_Minimap_24.6.1_Fabric_1.21.jar
- XaerosWorldMap_1.39.0_Fabric_1.21.jar
- YungsApi-1.21.1-Fabric-5.1.3.jar
- YungsBetterDesertTemples-1.21.1-Fabric-4.1.2.jar
- YungsBetterDungeons-1.21.1-Fabric-5.1.3.jar
- YungsBetterEndIsland-1.21.1-Fabric-3.1.1.jar
- YungsBetterJungleTemples-1.21.1-Fabric-3.1.2.jar
- YungsBetterMineshafts-1.21.1-Fabric-5.1.1.jar
- YungsBetterNetherFortresses-1.21.1-Fabric-3.1.3.jar
- YungsBetterOceanMonuments-1.21.1-Fabric-4.1.2.jar
- YungsBetterStrongholds-1.21.1-Fabric-5.1.2.jar
- YungsBetterWitchHuts-1.21.1-Fabric-4.1.1.jar
- YungsBridges-1.21.1-Fabric-5.1.1.jar
- YungsExtras-1.21.1-Fabric-5.1.1.jar

</details>

<details><summary>logs</summary>

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-11-22 03:42:30
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_746
	at knot//com.st0x0ef.stellaris.common.utils.Utils.changeDimension(Utils.java:88)
	at knot//com.st0x0ef.stellaris.common.network.packets.TeleportEntityToPlanetPacket.handle(TeleportEntityToPlanetPacket.java:54)
	at knot//dev.architectury.impl.NetworkAggregator.lambda$registerC2SReceiver$3(NetworkAggregator.java:108)
	at knot//dev.architectury.networking.transformers.PacketTransformer$1.inbound(PacketTransformer.java:47)
	at knot//dev.architectury.impl.NetworkAggregator.lambda$registerC2SReceiver$4(NetworkAggregator.java:102)
	at knot//dev.architectury.networking.fabric.NetworkManagerImpl$1.lambda$registerC2S$0(NetworkManagerImpl.java:58)
	at knot//net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.lambda$receive$0(ServerPlayNetworkAddon.java:72)
	at knot//net.minecraft.class_3738.run(class_3738.java:18)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
	at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
	at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
	at knot//net.minecraft.class_1255.method_18857(class_1255.java:145)
	at knot//net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810)
	at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.6.54_1
	Java Version: 21.0.5, Void
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Void
	Memory: 442466256 bytes (421 MiB) / 1398800384 bytes (1334 MiB) up to 2069889024 bytes (1974 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MiB): 258.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 19203.08
	Virtual memory used (MiB): 7883.07
	Swap memory total (MiB): 15258.00
	Swap memory used (MiB): 1194.75
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 3938.02, total: 3945.09
	Space in storage for workdir (MiB): available: 164630.06, total: 398416.63
	JVM Flags: 0 total; 
	Fabric Mods: 
		amplified_nether: Amplified Nether 1.2.6
		antixray: AntiXray 1.4.6
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		architectury: Architectury 13.0.8
		audaki_cart_engine: Audaki Cart Engine 3.1.1
		balanced-ice-boats: Balanced Ice Boats 1.0.0
		better_climbing: Better Climbing 3
		betterdeserttemples: YUNG's Better Desert Temples 1.21.1-Fabric-4.1.2
		betterdungeons: YUNG's Better Dungeons 1.21.1-Fabric-5.1.3
		betterendisland: YUNG's Better End Island 1.21.1-Fabric-3.1.1
		betterfortresses: YUNG's Better Nether Fortresses 1.21.1-Fabric-3.1.3
		betterjungletemples: YUNG's Better Jungle Temples 1.21.1-Fabric-3.1.2
		bettermineshafts: YUNG's Better Mineshafts 1.21.1-Fabric-5.1.1
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.21.1-Fabric-4.1.2
		betterstrongholds: YUNG's Better Strongholds 1.21.1-Fabric-5.1.2
			org_reflections_reflections: reflections 0.10.2
		betterwitchhuts: YUNG's Better Witch Huts 1.21.1-Fabric-4.1.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.10.2-1.21.1
			multipart_entities: MultipartEntities 1.7-1.21
		c2me: Concurrent Chunk Management Engine 0.3.0+alpha.0.295+1.21.1
			c2me-base: Concurrent Chunk Management Engine (Base) 0.3.0+alpha.0.295+1.21.1
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.3.0+alpha.0.295+1.21.1
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.3.0+alpha.0.295+1.21.1
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.3.0+alpha.0.295+1.21.1
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.3.0+alpha.0.295+1.21.1
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.3.0+alpha.0.295+1.21.1
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.3.0+alpha.0.295+1.21.1
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.3.0+alpha.0.295+1.21.1
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.3.0+alpha.0.295+1.21.1
			c2me-opts-dfc: Concurrent Chunk Management Engine (Optimizations/Density Function Compiler) 0.3.0+alpha.0.295+1.21.1
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.3.0+alpha.0.295+1.21.1
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.3.0+alpha.0.295+1.21.1
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.3.0+alpha.0.295+1.21.1
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.3.0+alpha.0.295+1.21.1
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.3.0+alpha.0.295+1.21.1
			c2me-rewrites-chunk-system: Concurrent Chunk Management Engine (Rewrites/Chunk System) 0.3.0+alpha.0.295+1.21.1
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.3.0+alpha.0.295+1.21.1
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.3.0+alpha.0.295+1.21.1
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.3.0+alpha.0.295+1.21.1
			com_ibm_async_asyncutil: asyncutil 0.1.0
			io_reactivex_rxjava3_rxjava: rxjava 3.1.8
			mixinsquared: MixinSquared 0.2.0-beta.6
			net_objecthunter_exp4j: exp4j 0.4.8
			org_jctools_jctools-core: jctools-core 4.0.5
			org_reactivestreams_reactive-streams: reactive-streams 1.0.4
		cardinal-components: Cardinal Components API 6.1.1
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-block: Cardinal Components API (blocks) 6.1.1
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
			cardinal-components-item: Cardinal Components API (items) 6.1.1
			cardinal-components-level: Cardinal Components API (world saves) 6.1.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.1
			cardinal-components-world: Cardinal Components API (worlds) 6.1.1
		carpet: Carpet Mod 1.4.147+v240613
		carpet-extra: Carpet Extra 1.4.148
		carryon: Carry On 2.2.2
		chunky: Chunky 1.4.16
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		combat_roll: Combat Roll 2.0.1+1.21.1
		combatnouveau: Combat Nouveau 21.1.1
		commonnetworking: Common Network 1.0.16-1.21.1
		computercraft: CC: Tweaked 1.114.0
			cc_tweaked_cobalt: cobalt 0.9.5
			com_jcraft_jzlib: jzlib 1.1.3
			io_netty_netty-codec-http: netty-codec-http 4.1.97
			io_netty_netty-codec-socks: netty-codec-socks 4.1.97
			io_netty_netty-handler-proxy: netty-handler-proxy 4.1.97
		debugify: Debugify 1.21.1+1.0
		deeperdarker: Deeper and Darker 1.3.2.1
			customportalapi: Custom Portal Api 0.0.1-beta66-1.21
		easyauth: Easy Authentication Mod 3.0.25
			at_favre_lib_bcrypt: bcrypt 0.10.2
			at_favre_lib_bytes: bytes 1.6.1
			com_mysql_mysql-connector-j: mysql-connector-j 8.2.0
			com_typesafe_config: config 1.4.3
			de_mkammerer_argon2-jvm: argon2-jvm 2.11
			de_mkammerer_argon2-jvm-nolibs: argon2-jvm-nolibs 2.11
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			net_java_dev_jna_jna: jna 5.13.0
			org_apache_commons_commons-text: commons-text 1.10.0
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_mongodb_bson: bson 4.11.1
			org_mongodb_mongodb-driver-core: mongodb-driver-core 4.11.1
			org_mongodb_mongodb-driver-sync: mongodb-driver-sync 4.11.1
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		fabric-api: Fabric API 0.107.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.69+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.17+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.1+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.1+7fd4837519
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.2.0+e49211d819
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.22+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.4.0+0f6c53cd19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.1+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		ferritecore: FerriteCore 7.0.2-hotfix
		forgeconfigapiport: Forge Config API Port 21.1.2
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		formidulus: Formidulus 0.1.0-beta
			mm: Manningham Mills 2.3
			yayconfig: YayConfig 1.0.1
		geckolib: GeckoLib 4 4.7
		glow_ink_plus: Glow Ink Plus Mod 1.2
		herdspanic: Herds Panic 1.1.1
		icarus: Icarus 4.2.0
		improved_anvils: Improved Anvils 1.1.1-1.21
		incendium: Incendium 5.4.3
		item_components: Item Components 1.1
		java: OpenJDK 64-Bit Server VM 21
		ledger: Ledger 1.3.4
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
				packet_tweaker: Packet Tweaker 0.5.1+24w03b
		lithium: Lithium 0.13.1
		minecraft: Minecraft 1.21.1
		modernfix: ModernFix 5.19.5+mc1.21.1
		monsters_in_the_closet: Monsters in the Closet 1.0.3+1.21
		mr_desert_scourge: Desert Scourge 1.2
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v4.4.4
		mr_edf_remastered: Ender Dragon Fight Remastered 5.0-beta4
		mr_skippy_pearls: Skippy Pearls 1.21
		mr_wandering_illusioneratlasplays: Wandering Illusioner 1.1.0
		mr_withering_heights: Withering Heights: Revamped Wither 1-v1.0
		netheriteextras: Netherite Extras 0.4.0+mc1.21
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		nullscape: Nullscape 1.2.9
		owo: oωo 0.12.15+1.21
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		pathspeed: PathSpeed 1.21_1.0.0
		playeranimator: Player Animator 2.0.0-alpha1+1.21
		puzzleslib: Puzzles Lib 21.1.22
		recipecooldown: Recipe Cooldown 1.17.1-1.0.0
		resourcefulconfig: Resourcefulconfig 3.0.7
		scalablelux: ScalableLux 0.1.0+fabric.26c6e72
		servux: Servux 0.3.7
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
		skinrestorer: SkinRestorer 2.1.0+1.21-fabric
		spark: spark 1.10.109
		stellaris: Stellaris 1.1.7
			sky_aesthetics: Sky Aesthetics 1.2.5
			team_reborn_energy: Energy 4.1.0
		styledchat: Styled Chat 2.6.0+1.21
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
			player-data-api: Player Data API 0.6.0+1.21
			predicate-api: Predicate API 0.5.1+1.21
		surveyor: Surveyor Map Framework 0.6.25+1.21
			folk_sisby_kaleido-config: kaleido-config 0.3.1+1.3.2
		swordblockingmechanics: Sword Blocking Mechanics 21.1.0
		tab: TAB 5.0.1
		terralith: Terralith 2.5.6
		toms_storage: Tom's Simple Storage Mod 2.0.11
		tool_trims: Tool Trims 2.2.1
		travelersbackpack: Traveler's Backpack 10.1.3
		trinkets: Trinkets 3.10.0
		tt20: TT20 0.7.0
			net_snackbag_shit_shit: shit 1.2.3
		voicechat: Simple Voice Chat 1.21.1-2.5.25
		worldedit: WorldEdit 7.3.8+6939-7d32b45
		xaerominimap: Xaero's Minimap 24.6.1
		xaeroworldmap: Xaero's World Map 1.39.0
		yungsapi: YUNG's API 1.21.1-Fabric-5.1.3
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.21.1-Fabric-5.1.1
		yungsextras: YUNG's Extras 1.21.1-Fabric-5.1.1
	Server Running: true
	Player Count: 1 / 20; [class_3222['Fatty2021'/74, l='ServerLevel[world]', x=8.50, y=602.40, z=2.50]]
	Active Data Packs: vanilla, fabric, amplified_nether, betterdeserttemples (incompatible), betterdungeons (incompatible), betterendisland (incompatible), betterfortresses (incompatible), betterjungletemples (incompatible), bettermineshafts (incompatible), betteroceanmonuments (incompatible), betterstrongholds (incompatible), betterwitchhuts (incompatible), bosses_of_mass_destruction, carryon (incompatible), combat_roll, computercraft (incompatible), deeperdarker (incompatible), easyauth, fabric-convention-tags-v2, formidulus, glow_ink_plus (incompatible), icarus, incendium, ledger, mr_desert_scourge, mr_dungeons_andtaverns, mr_edf_remastered, mr_skippy_pearls (incompatible), mr_wandering_illusioneratlasplays, mr_withering_heights (incompatible), netheriteextras, nullscape, server_translations_api, stellaris, swordblockingmechanics (incompatible), terralith, toms_storage, tool_trims, travelersbackpack, trinkets, yungsapi (incompatible), yungsbridges (incompatible), yungsextras (incompatible), file/bat membranes v1.0.10 (MC 1.21-1.21.3).zip, file/darcenos-minecarts-slower-1.4.zip, file/double shulker shells v1.3.9 (MC 1.21-1.21.3).zip, file/dragon drops v1.3.9 (MC 1.21-1.21.3).zip, file/ender chest always drops v1.0.1 (MC 1.21-1.21.3).zip, file/name colors v1.0.7 (MC 1.21-1.21.3).zip, file/player head drops v1.1.9 (MC 1.21-1.21.3).zip, file/silk touch budding amethyst v1.0.1 (MC 1.21-1.21.3).zip, file/Better Rail Recipe.zip, file/Mend It Yourself.zip, file/VanillaTweaks_c816160_MC1.21-1.21.3.zip, combatnouveau:halved_sweeping_damage, file/stackable-potions-1.0+1.21.zip
	Available Data Packs: amplified_nether, betterdeserttemples (incompatible), betterdungeons (incompatible), betterendisland (incompatible), betterfortresses (incompatible), betterjungletemples (incompatible), bettermineshafts (incompatible), betteroceanmonuments (incompatible), betterstrongholds (incompatible), betterwitchhuts (incompatible), bosses_of_mass_destruction, bundle, carryon (incompatible), combat_roll, combatnouveau:halved_sweeping_damage, computercraft (incompatible), deeperdarker (incompatible), easyauth, fabric, fabric-convention-tags-v2, file/Better Rail Recipe.zip, file/Mend It Yourself.zip, file/VanillaTweaks_c816160_MC1.21-1.21.3.zip, file/bat membranes v1.0.10 (MC 1.21-1.21.3).zip, file/darcenos-minecarts-slower-1.4.zip, file/double shulker shells v1.3.9 (MC 1.21-1.21.3).zip, file/dragon drops v1.3.9 (MC 1.21-1.21.3).zip, file/ender chest always drops v1.0.1 (MC 1.21-1.21.3).zip, file/name colors v1.0.7 (MC 1.21-1.21.3).zip, file/player head drops v1.1.9 (MC 1.21-1.21.3).zip, file/silk touch budding amethyst v1.0.1 (MC 1.21-1.21.3).zip, file/stackable-potions-1.0+1.21.zip, formidulus, glow_ink_plus (incompatible), icarus, incendium, ledger, mr_desert_scourge, mr_dungeons_andtaverns, mr_edf_remastered, mr_skippy_pearls (incompatible), mr_wandering_illusioneratlasplays, mr_withering_heights (incompatible), netheriteextras, nullscape, server_translations_api, stellaris, swordblockingmechanics (incompatible), terralith, toms_storage, tool_trims, trade_rebalance, travelersbackpack, trinkets, vanilla, yungsapi (incompatible), yungsbridges (incompatible), yungsextras (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: -265898018982099860
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

</details>

**Comment by st0x0ef** [comment]
This bug has already been fixed in 1.2.0-beta1
